### ISSUE TITLE
Add support to use BOARD mode

### ISSUE THREAD

**Issue by filips123** [RPi-Distro/python-gpiozero#601] opened 2017-11-03 14:33 UTC
Add support to use BOARD mode. BCM mode should be default. Mode could be at the beginning of the program (as in RPi.GPIO) or for each device separately (`led = LED(7, mode=BOARD)`).

**Comment by bennuttall** [comment] 2017-11-03 14:39
Duplicate of #467.

This has been debated back-and-forth. We distinctly only supported a single numbering system in the beginning, to keep things simple. Your best bet is to use a port label or the [pinout command line tool](http://gpiozero.readthedocs.io/en/stable/cli_tools.html#pinout).

**Closed by bennuttall** 2017-11-03 14:39 UTC

**Comment by filips123** [comment] 2017-11-03 14:54
If you were to support both ways, but one would be default, it would not be more complicated.
In addition, I am interested in how to support the older versions of Raspberry Pi, which have a different labeling without changes.

**Comment by bennuttall** [comment] 2017-11-03 16:04
But any resources people make will vary - some using one numbering system, some using another.

GPIO Zero works with any Pi model, as BCM pin numbers work wherever they're located on the board. And the `pinout` tool will show you an accurate pinout diagram for the Pi you're on.
