### ISSUE TITLE
HCSR04 sensor cannot record <15cm distances in Pi Zero

### ISSUE THREAD

**Issue by topshed** [RPi-Distro/python-gpiozero#537] opened 2017-02-23 11:59 UTC
On a Pi 3 I connect up an HCSR04 distance sensor using the circuit as described in the Python gpiozero documentation. then using the example code I record distance measurements. It all works as expected and I can register distances from about 1.5 cm up to 1m.

Take the SD card out and pop it in a Pi Zero. Then swap over the wires connecting the circuit to the GPIO pins. 

The same code still works but is only able to record short distances down to ~14.5cm. Anything less just registers as 0.0.

I've tried several different Pi Zeros, different HCSR04 sensors and using different GPIO pins but the results are always the same.

It looks like it's getting stuck in here.

`            if self._echo.wait(0.04) and self._echo_fall is not None and self._echo_rise is not None:
                distance = (self._echo_fall - self._echo_rise) * self.speed_of_sound / 2.0
                self._echo_fall = None
                self._echo_rise = None
                return min(1.0, distance / self._max_distance)
            else:
                # If we only saw one edge it means we missed the echo because
                # it was too fast; report minimum distance
                return 0.0`

I don't think it is an inherent hardware problem. The alternative HCSR04 library [https://github.com/alaudet/hcsr04sensor](https://github.com/alaudet/hcsr04sensor) works fine on Pi Zero.

There is a brief discussion on the Pi forum: 
https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=174947&p=1116806#p1116806

**Comment by lurch** [comment] 2017-02-23 14:07
Yeah, this is a known problem, unfortunately https://github.com/RPi-Distro/python-gpiozero/search?q=distance+sensor&state=open&type=Issues&utf8=%E2%9C%93

Closing this for now as a duplicate of #385

**Closed by lurch** 2017-02-23 14:07 UTC
